/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    // Status badge colors (composed dynamically in getStatusColor / getPaymentColor)
    'bg-success-container', 'text-on-success-container',
    'bg-warning-container', 'text-on-warning-container',
    'bg-primary-container', 'text-on-primary-container',
    'bg-error-container', 'text-on-error-container',
    'bg-surface-container-highest', 'text-on-surface-variant',
    'bg-surface-variant', 'text-on-surface',
    'bg-secondary-container', 'text-on-secondary-container',
    'bg-tertiary-container', 'text-on-tertiary-container',
    'bg-secondary-fixed', 'text-on-secondary-fixed',
    'text-primary', 'text-tertiary-container', 'text-error', 'text-success',
    'bg-success', 'bg-warning', 'bg-error', 'bg-outline',
    'border-success', 'border-warning', 'border-error',
    'border-success/20', 'border-warning/20', 'border-error/20', 'border-primary/20',
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Premium tech palette (customer-facing site)
        ink: {
          50: "#f7f8fa", 100: "#eef0f4", 200: "#dadee6", 300: "#b9c0cd",
          400: "#8e96a8", 500: "#6b7385", 600: "#4a5160", 700: "#363c47",
          800: "#22262e", 900: "#13161c", 950: "#0a0c11",
        },
        accent: {
          50: "#ecfaff", 100: "#cef3ff", 200: "#a2e8ff", 300: "#60d8ff",
          400: "#18bdfa", 500: "#009fe0", 600: "#007fbb", 700: "#066698",
          800: "#0b557b", 900: "#0f4767", 950: "#072d44",
        },
        brand: { DEFAULT: "#0EA5E9", dark: "#0284C7", light: "#7DD3FC" },

        // Material Design tokens (existing admin dashboard)
        "on-error-container": "#93000a",
        "surface-dim": "#d8d9e3",
        "on-surface-variant": "#414754",
        "on-tertiary-container": "#0e0200",
        "primary-fixed": "#d8e2ff",
        "surface-variant": "#e0e2ec",
        "outline": "#727785",
        "on-tertiary-fixed-variant": "#783100",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2d3038",
        "on-tertiary-fixed": "#341100",
        "tertiary": "#9e4300",
        "surface-bright": "#f9f9ff",
        "surface-container": "#ecedf7",
        "secondary-container": "#d0e1fb",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#001a41",
        "surface-tint": "#005bc0",
        "on-primary-container": "#ffffff",
        "primary-fixed-dim": "#adc7ff",
        "on-secondary-container": "#54647a",
        "background": "#f9f9ff",
        "primary-container": "#1a73e8",
        "surface": "#f9f9ff",
        "tertiary-fixed": "#ffdbcb",
        "primary": "#005bbf",
        "secondary": "#505f76",
        "secondary-fixed": "#d3e4fe",
        "on-primary": "#ffffff",
        "surface-container-high": "#e6e8f2",
        "on-secondary-fixed": "#0b1c30",
        "inverse-primary": "#adc7ff",
        "surface-container-highest": "#e0e2ec",
        "secondary-fixed-dim": "#b7c8e1",
        "on-surface": "#191c23",
        "inverse-on-surface": "#eff0fa",
        "surface-container-low": "#f2f3fd",
        "outline-variant": "#c1c6d6",
        "error-container": "#ffdad6",
        "on-background": "#191c23",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#004493",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#ffb691",
        "tertiary-container": "#c55500",
        "on-secondary-fixed-variant": "#38485d",
        "on-secondary": "#ffffff",

        // Success semantic tokens (green — used by status badges, warranty, alerts)
        "success": "#1b6d2f",
        "on-success": "#ffffff",
        "success-container": "#a8f5a2",
        "on-success-container": "#00210a",

        // Warning semantic tokens (amber — used by "Repairing" / "In Progress" badges)
        "warning": "#7c5800",
        "on-warning": "#ffffff",
        "warning-container": "#ffe08d",
        "on-warning-container": "#261a00",

        // Additional secondary-fixed tokens used by TicketDetails badges
        "on-secondary-fixed": "#0b1c30",
        "on-primary-fixed": "#001a41",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "14px",
        "2xl": "20px",
        "3xl": "28px",
        "full": "9999px",
      },
      spacing: {
        "md": "16px",
        "lg": "24px",
        "margin-mobile": "16px",
        "xs": "4px",
        "xl": "32px",
        "sm": "8px",
        "base": "8px",
        "container-max": "1280px",
        "gutter": "20px",
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['Inter', 'system-ui', 'sans-serif'],
        // Material aliases used by existing admin pages
        "label-md": ["Inter"], "headline-lg-mobile": ["Inter"], "body-lg": ["Inter"],
        "title-lg": ["Inter"], "body-md": ["Inter"], "headline-lg": ["Inter"],
        "code": ["JetBrains Mono", "monospace"], "headline-md": ["Inter"],
        "display-lg-mat": ["Inter"],
      },
      fontSize: {
        '2xs': ['10px', { lineHeight: '14px' }],
        'display-xl': ['clamp(2.75rem, 6vw, 5rem)', { lineHeight: '1.05', letterSpacing: '-0.035em', fontWeight: '700' }],
        'display-lg': ['clamp(2.25rem, 5vw, 4rem)', { lineHeight: '1.08', letterSpacing: '-0.03em', fontWeight: '700' }],
        'display-md': ['clamp(1.75rem, 3.5vw, 2.75rem)', { lineHeight: '1.15', letterSpacing: '-0.025em', fontWeight: '700' }],
        // Material sizes used by existing admin pages
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "title-lg": ["18px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "code": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
      boxShadow: {
        'soft': '0 2px 12px rgba(15, 23, 42, 0.04), 0 1px 3px rgba(15, 23, 42, 0.06)',
        'soft-lg': '0 12px 40px rgba(15, 23, 42, 0.08), 0 4px 12px rgba(15, 23, 42, 0.04)',
        'glow': '0 0 60px rgba(14, 165, 233, 0.35)',
        'glow-sm': '0 0 24px rgba(14, 165, 233, 0.25)',
      },
      backgroundImage: {
        'grid-light': "linear-gradient(rgba(15,23,42,0.04) 1px, transparent 1px), linear-gradient(90deg, rgba(15,23,42,0.04) 1px, transparent 1px)",
        'radial-fade': 'radial-gradient(circle at 50% 0%, rgba(14,165,233,0.18), transparent 60%)',
      },
      keyframes: {
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
      },
      animation: {
        'fade-up': 'fade-up 0.6s ease-out forwards',
        'shimmer': 'shimmer 2.4s linear infinite',
        'float': 'float 6s ease-in-out infinite',
        'pulse-soft': 'pulse-soft 3s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
